# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2871081c9f985fbed930bfcb778f6674199362bc296c56501e96501892ec8d52ea7b22db770e1a6aefecc7e4fa2052505e071692e2491596608cb95e87e608be

test:
  secret_key_base: 489abfbdd64965e88cac102be6803ae7563669fcf5890bde82ad7c9cefc852676d6beff40204f9a0b99a3a62e094556cf507281887b4ce27aa71e8e5a570ef11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
